version: "3.8"

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - internal-grafana-pod
  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - internal-grafana-pod
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
    restart: unless-stopped
    volumes:
      - /etc/docker_stack/stack_server/bifrost/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - internal-grafana-pod
volumes:
  grafana_data:
  prometheus_data:
networks:
  internal-grafana-pod:
    internal: true